// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServidorImpresion.Context;

#nullable disable

namespace ServidorImpresion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("ServidorImpresion.Models.HistorialImpresionCupon", b =>
                {
                    b.Property<int>("HistorialImpresionCuponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodMaquina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Enviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaImpresion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImpresionCuponId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Impreso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreImpresora")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSala")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSorteo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .HasColumnType("TEXT");

                    b.Property<long>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistorialImpresionCuponId");

                    b.ToTable("HistorialImpresionCupon", (string)null);
                });

            modelBuilder.Entity("ServidorImpresion.Models.ImpresionCupon", b =>
                {
                    b.Property<int>("ImpresionCuponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodMaquina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Enviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaImpresion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Impreso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreImpresora")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSala")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSorteo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .HasColumnType("TEXT");

                    b.Property<long>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImpresionCuponId");

                    b.ToTable("ImpresionCupon", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
